### ISSUE TITLE
move function returns None

### ISSUE THREAD

**Issue by jorgesumle** [zkan/tictactoe#1]
jorge@jorge-All-Series:~/Código/Repositorios/tictactoe$ python tictactoe_minimax.py 

New game!
Traceback (most recent call last):
  File "tictactoe_minimax.py", line 100, in <module>
    t.play_game()
  File "tictactoe_minimax.py", line 52, in play_game
    self.board[move - 1] = char
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

**Comment by zkan** [comment]
Just merge the final code back to master branch. Please try again. @jorgesumle
